### ISSUE TITLE
Add instructions for querying or adding a project-level SSH key

### ISSUE THREAD

**Issue by alexellis** [jsiebens/terraform-equinix-faasd#2]
If you could add instructions for querying or adding a project-level SSH key, it would be most helpful.

I can't seem to make any progress here because I can't find a way to query the IDs of the project ssh keys, after adding them via the UI. The `metal` CLI also only lists user-level SSH keys.

**Comment by jsiebens** [comment]
The Equinix Metal Terraform provider has a datasource to retrieve a Project SSH key and its attributes
- https://registry.terraform.io/providers/equinix/metal/latest/docs/data-sources/project_ssh_key

An example is now available to illustrate this
See commit 1f7567a
